# Generated by Django 4.2.20 on 2025-04-25 08:22

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', core.models.CustomUserManager()),
            ],
        ),
    ]
