# Generated by Django 4.2.20 on 2025-04-25 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='org',
            field=models.ForeignKey(blank=True, help_text='Organization this user belongs to (not required for super-admins).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.org'),
        ),
    ]
