# Generated by Django 4.2.20 on 2025-05-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customuser_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='run_url',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
